sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: an666666
    url: jdbc:mysql://${sky.datasource.host}:${sky.datasource.port}/${sky.datasource.database}?useSSL=false&serverTimezone=UTC&characterEncoding=utf8&rewriteBatchedStatements=true
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: ${ALIBABA_ACCESS_KEY:}
    access-key-secret: ${ALIBABA_SECRET_KEY:}
    bucket-name: bucket-of-sky
